### ISSUE TITLE
Can I play online？

### ISSUE THREAD

**Issue by SasoriJr** [smealum/regionthree#16]
Hi developer. First, I'd like to thank you for bringing us the freedom.

Second, I've searched and didn't find a answer, that's why I am here. I plan to import a JP game, Puyo Puyo Tetris, I think it has online play. My doubt is if I'll have the ability to play it online once I boot it on my American 3DS.

Can I play any region game online? Thank you

**Comment by smealum** [comment]
depends on the game. online functionality itself is fine afaik, but you
can't update your game, meaning that if online relies on a game update it
won't be accessible.

**Comment by SasoriJr** [comment]
Oh, I see. Being able to play online is a relief! I'm gonna see if this game in particular needs an update. Thank you kindly

**Comment by m9650827** [comment]
## NAVER - http://www.naver.com/

9650827@naver.com 님께 보내신 메일 <[regionthree] Can I play online？ (#16)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---

**Comment by smealum** [comment]
just to be safe you should probably ask someone who had the game with
region three/four if it works

**Comment by m9650827** [comment]
## NAVER - http://www.naver.com/

9650827@naver.com 님께 보내신 메일 <Re: [regionthree] Can I play online？ (#16)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---

**Comment by SasoriJr** [comment]
Yep, I'll do it. Thanks for the tip (｀・∀・´)
