### ISSUE TITLE
Firmware question

### ISSUE THREAD

**Issue by emperorbob** [smealum/regionthree#5]
So I managed to get this working on a 4.5 3DS, and I have noticed that newer games don't load on the system. The screen just remains black and the 3DS needs to be powered off. 

Is this a documented issue? Do the newer games use something an older firmware can't handle?

**Comment by smealum** [comment]
"Do the newer games use something an older firmware can't handle?" yes
regionthree bypasses updates but that doesn't change the fact that some games _need_ newer firmware versions to run.
that being said, in the vast majority of cases (if not always) the required firmware version is lower than the update version present on the gamecard.
also, be aware that games that come loaded with update 6.0+ use different cryptography and therefore savegames may show up as corrupted on lower firmware versions even if they're not.
all in all, trying to run newer games on 4.x through regionthree is not recommended.

**Comment by emperorbob** [comment]
All I needed to know, thanks.
